sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '8'
cache:
- node_modules
branches:
   except:
   - stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm config set package-lock false
- npm i -g npm@^5.7.1
install:
- npm install @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
env:
  global:
  - secure: eM+m5vGWUkXz0p2SFQd9XflKBhH8BUrkY8PzQ5wYBWG6irB53k/cTdBcVMeBQR6fe+pN/Rha7VBQOTi1fc9xNbdcAU0iN9NKllEV+MJheGTSD5wkTuHgflNatdste8oD1OUNDeFsAFYpRdN6vO7BSnbiDI5jEOusbAvS/uGE8RLT6O0f6Vfb2fVBxYE43Zlvq8+I7z7QhDw1Gu83cBsSxy3wiW7KlWrLY+hppSgQ4eAopZm/f+aQ+YkTJTjPerQ5Dr1qIOIEgzPSCGO3VaaGIXULq3rxHkx4NaQGfoNe1YNIuuCh5Bt0rPuIN+GlNYB68suT9U0zJQ/Cua2Rvy5h0G0hlIrBLyEJHzBar7YcqoPc+lqWcgSJfYYgnQXzTvpcxRFgwHbDSGhERRuoAf6bJgKprt/pDoavAWogLd0nxSYF3aSb6rcME9CdBlUwqh/iPvY+sOJEWHLCasuSXB2ZbaaF9ltHDbO+p0u1OpjnzlpmA3mG7g53q7TCP6yiiiQ5bBorViR75Y/xNkhjs4wbNvpgi2vdVbPxU0wmcZMWcMblchGKfK5X+HieIgaBuja+P6NWAZaleKr3o0dD3eY99Mq38ivn/LTaXr1k+SVDZLqBauJ4a4+oy9LmxqNwVgiRuhWLmDnOOyFfBG5OznCfzCBfVIo9tdsuSWf8STVo+WU=
  - secure: NheA8ZyyBCJ9j7A3n7GlmCBjzNQkMYRXAAnbgHKD7glAON0MIr79Fr/xQJfDp3cnqPpQsXbQAY/C2gTakSwBvaRADCog3kfdBMIqgAx4jJnXOVJiqXiau3eC3dR7DpVpdcRtuGbpNtCBs5SU9RRWmEBhF2cWxEI/S+wZjlDgrdiq/JVI5BAYj4J+Qi01S3x9Rbfetwo+TtY/E4KbSk6orRU+CSpRHeCFhLw2B6BsLzKec2Dsqn6DscS/yRm1t7Yzpmp0tl3i9+FLdbhZzJdeExY9A4tp21y3rR45dCHrXP5Uk1mVAbyW3XjMStrQ6peC9WuvUhcemUDEdALZjH5Ej1DYdPYYqfXeCEx9FFmy16iUY9QrKy78avmKd35QEBJObgfOEyU5OH8RxHKu5pVDnws7NSJcoN9BPs5678jHysjPyFyRdJRAEKfqeEr2z3oVCHqNBmvxh54Y+L+ecknqyvPTfoM2FzVtJMSawERvTuckYa8uOH8ls2nf2NN2VCrPhWobWh6ZIT7LUlGp4St6tcVH2zf6XVAGmcwDvN/BBQUJm5gEvcSx3h5SxyCP8dbrzZIo/GFcKUfJrtJxnDpkjfXS0WYV5jc+zBk1mCAqo2d7tTwVKF5zK3Y004f5WCF6yQQ53Vpkcfh2CE9xBSD3LyeDRNYeS3S5v1yd0N2M0bc=
